Repository alexa/ask-toolkit-for-vscode, pull requests merged in 2020-11, with the labels that each got.

#57 fix: iconpath for quick input button for vscode 1.51.1, update package lock and tests for new version
  package-lock.json
  package.json
  src/askContainer/commands/viewAllSkills.ts
  test/testUtilities.ts
Labels: bug

#51 feat: add default aws region for create hosted skill
  media/createSkill/createSkill.html
  media/createSkill/createSkill.js
  src/askContainer/webViews/createSkillWebview.ts
  src/utils/createSkillHelper.ts
Labels: enhancement

#63 feat: add dynamic content to welcome screen
  media/welcomeScreen/welcomeScreen.html
  media/welcomeScreen/welcomeScreen.js
  src/askContainer/commands/welcome.ts
  src/askContainer/treeViews/treeViewProviders/helpViewProvider.ts
  src/askContainer/webViews/welcomeScreenWebview.ts
  src/constants.ts
  src/extension.ts
Labels: enhancement

#68 Fix AplRenderUtils, to use all parameters in APL document during APL preview
  media/previewApl/aplRenderUtils.js
Labels: APL Previewer, bug

#70 Add github actions to run extension tests on PRs/ pushes
  .github/workflows/extensionTests.yml
  test/extension.test.ts
  test/index.ts
  test/runtime/utils/profileHelper.test.ts
Labels: enhancement

#71 fix: add condition to apl renderer content for invalid parameter names
  media/previewApl/aplRenderUtils.js
Labels: APL Previewer, bug
